# Generated by Django 5.2.1 on 2025-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='bilder/')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
